# Generated by Django 5.1.5 on 2025-04-07 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descripion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='event',
            name='registered',
            field=models.ManyToManyField(default='', related_name='registered_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='rules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
