# Generated by Django 5.1.5 on 2025-04-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_descripion_event_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registered',
        ),
    ]
