# Generated by Django 5.1.5 on 2025-04-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Live', 'Live'), ('Upcoming', 'Upcoming'), ('Ended', 'Ended')], default='', max_length=15),
        ),
    ]
