# Generated by Django 5.1.5 on 2025-04-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='status',
            new_name='event_status',
        ),
        migrations.AddField(
            model_name='event',
            name='event_tags',
            field=models.CharField(choices=[('Hackathon', 'Hackathon'), ('DSA', 'DSA'), ('UI/UX', 'UI/UX'), ('Ideation', 'Ideation')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='open_to_choices',
            field=models.CharField(choices=[('Open to Everyone', 'Open to Everyone'), ('Kaziranga Only', 'Kaziranga Only'), ('BS Degree Students', 'BS Degree Students'), ('All', 'All')], default='', max_length=20),
        ),
    ]
