# Generated by Django 5.1.5 on 2025-04-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(choices=[('ONLNIE', 'Online'), ('OFFLINE', 'Offline'), ('HYBRID', 'Hybrid')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('UPCOMING', 'Upcoming'), ('ENDED', 'Ended')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_tags',
            field=models.CharField(choices=[('HACKATHON', 'Hackathon'), ('DSA', 'DSA'), ('UI/UX', 'UI/UX'), ('IDEATION', 'Ideation')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='open_to_choices',
            field=models.CharField(choices=[('OPEN', 'Open to Everyone'), ('KAZIRANGA', 'Kaziranga Only'), ('BS', 'BS Degree Students'), ('ALL', 'All')], default='', max_length=20),
        ),
    ]
