# Generated by Django 5.1.5 on 2025-04-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_event_location_alter_event_event_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('HYBRID', 'Hybrid')], default='', max_length=20),
        ),
    ]
