# Generated by Django 5.2.7 on 2025-11-30 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('events', '0009_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='clubs.community'),
        ),
    ]
