# Generated by Django 5.1.5 on 2025-01-29 05:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='intro',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='announcement',
            name='message',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='announcement',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='summary',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='announcement',
            name='use_case',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
