# Generated by Django 5.1.5 on 2025-01-29 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_intro_announcement_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 5, 30, 32, 143110)),
        ),
    ]
