# Generated by Django 5.1.5 on 2025-01-29 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_announcement_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(blank=True, choices=[('E', 'Educational'), ('M', 'Meetup'), ('C', 'Club'), ('MI', 'Miscellaneous'), ('Ev', 'Event')], default='MI', max_length=2),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 5, 31, 10, 750893)),
        ),
    ]
