# Generated by Django 5.1.5 on 2025-01-29 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_announcement_category_alter_announcement_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(blank=True, choices=[('FL', 'Foundation'), ('DP', 'Diploma(Programming)'), ('DS', 'Diploma(Data Science)'), ('BSC', 'BSc'), ('BS', 'BS'), ('All', 'All Levels')], default='All', max_length=21),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 5, 31, 46, 513254)),
        ),
    ]
