# Generated by Django 5.1.5 on 2025-01-29 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_announcement_target_audience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='help_format',
            field=models.BooleanField(choices=[(1, 'On'), (0, 'Off')], default=1),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 5, 32, 36, 73158)),
        ),
    ]
