# Generated by Django 5.1.5 on 2025-01-29 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_announcement_help_format_alter_announcement_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.TextField(default='Admin'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 5, 35, 48, 354999)),
        ),
    ]
