# Generated by Django 5.2.7 on 2025-11-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('head', models.CharField(max_length=100)),
                ('member_count', models.IntegerField(default=0)),
                ('description', models.TextField(help_text='Rich text description (supports HTML/Markdown)')),
                ('join_form_link', models.URLField(max_length=500)),
                ('logo', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=10)),
                ('theme', models.CharField(choices=[('CHESS', 'Chess'), ('PROGRAMMING', 'Programming'), ('SPIRITUALITY', 'Spirituality'), ('POETRY', 'Poetry'), ('MUSIC', 'Music'), ('SPORTS', 'Sports'), ('ARTS', 'Arts'), ('DEBATE', 'Debate'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Communities',
                'ordering': ['-created_on'],
            },
        ),
    ]
