# Generated by Django 5.1.5 on 2025-04-20 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=150)),
                ('article', models.TextField()),
                ('achievement', models.CharField(max_length=50)),
                ('achievement_tag', models.CharField(choices=[('Study', 'Student'), ('DSA', 'DSA'), ('Development', 'Development'), ('Hackathon', 'Hackathon'), ('Research', 'Research'), ('Internship', 'Internship'), ('Job', 'Job'), ('Contest Win', 'Contest Win'), ('Misc', 'Misc')], max_length=20)),
                ('achiever', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
