# Generated by Django 5.1.5 on 2025-04-20 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_of_fame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
