# Generated by Django 5.1.5 on 2025-04-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_of_fame', '0002_achievement_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='cover_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
