# Generated by Django 5.1.5 on 2025-04-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_of_fame', '0004_alter_achievement_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='cover_img',
            field=models.URLField(),
        ),
    ]
